config/routes.rb
AaSample1782::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :activities
  resources :days
  resources :adventures

  root :to => "adventures#index"
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :description

  belongs_to :day
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/adventure.rb
class Adventure < ActiveRecord::Base
  attr_accessible :name, :days_attributes

  has_many :days
  accepts_nested_attributes_for :days
end

app/models/day.rb
class Day < ActiveRecord::Base
  attr_accessible :number, :activities_attributes

  has_many :activities
  accepts_nested_attributes_for :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < InheritedResources::Base
end

app/controllers/adventures_controller.rb
class AdventuresController < InheritedResources::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/days_controller.rb
class DaysController < InheritedResources::Base
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/adventures_helper.rb
module AdventuresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br />
    <%= f.text_field :day %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <tr>
    <th>Day</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @activities.each do |activity| %>
  <tr>
    <td><%= activity.day %></td>
    <td><%= link_to 'Show', activity %></td>
    <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
    <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Day:</b>
  <%= @activity.day %>
</p>


<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/adventures/_form.html.erb
<%= form_for(@adventure) do |f| %>
  <% if @adventure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adventure.errors.count, "error") %> prohibited this adventure from being saved:</h2>

      <ul>
      <% @adventure.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adventures/edit.html.erb
<h1>Editing adventure</h1>

<%= render 'form' %>

<%= link_to 'Show', @adventure %> |
<%= link_to 'Back', adventures_path %>

app/views/adventures/index.html.erb
<h1>Listing adventures</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @adventures.each do |adventure| %>
  <tr>
    <td><%= adventure.name %></td>
    <td><%= link_to 'Show', adventure %></td>
    <td><%= link_to 'Edit', edit_adventure_path(adventure) %></td>
    <td><%= link_to 'Destroy', adventure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Adventure', new_adventure_path %>

app/views/adventures/new.html.erb
<h1>New adventure</h1>

<%= render 'form' %>

<%= link_to 'Back', adventures_path %>

app/views/adventures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @adventure.name %>
</p>


<%= link_to 'Edit', edit_adventure_path(@adventure) %> |
<%= link_to 'Back', adventures_path %>

app/views/days/_form.html.erb
<%= form_for(@day) do |f| %>
  <% if @day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% @day.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :adventure %><br />
    <%= f.text_field :adventure %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/days/edit.html.erb
<h1>Editing day</h1>

<%= render 'form' %>

<%= link_to 'Show', @day %> |
<%= link_to 'Back', days_path %>

app/views/days/index.html.erb
<h1>Listing days</h1>

<table>
  <tr>
    <th>Adventure</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @days.each do |day| %>
  <tr>
    <td><%= day.adventure %></td>
    <td><%= link_to 'Show', day %></td>
    <td><%= link_to 'Edit', edit_day_path(day) %></td>
    <td><%= link_to 'Destroy', day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Day', new_day_path %>

app/views/days/new.html.erb
<h1>New day</h1>

<%= render 'form' %>

<%= link_to 'Back', days_path %>

app/views/days/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Adventure:</b>
  <%= @day.adventure %>
</p>


<%= link_to 'Edit', edit_day_path(@day) %> |
<%= link_to 'Back', days_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AaSample1782</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>